application:
  routes:
    - /=http://changedetection.cloud.lazycat.app.changedetectionio.lzcapp:5000
  subdomain: changedetection

services:
  changedetection:
    image: embed:changedetection
    binds:
      - /lzcapp/var/datastore:/datastore
    environment:
      - PORT=5000
      - LISTEN_HOST=0.0.0.0
      - PLAYWRIGHT_DRIVER_URL=ws://sockpuppet.cloud.lazycat.app.changedetectionio.lzcapp:3000
      - HIDE_REFERER=true
      - DISABLE_VERSION_CHECK=true
      - FETCH_WORKERS=10
      - MINIMUM_SECONDS_RECHECK_TIME=3
      - SCREENSHOT_MAX_HEIGHT=16000
      - LOGGER_LEVEL=DEBUG

  sockpuppet:
    image: embed:sockpuppet
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - MAX_CONCURRENT_CHROME_PROCESSES=10
      - LOG_LEVEL=DEBUG
